name: Pre-release

on:
  push:
    branches:
      - next
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - 'package.json'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test

  # Temporarily disable prerelease job
  # prerelease:
  #   name: Prerelease
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
  #   env:
  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 14.x

  #     - name: Cache node_modules
  #       id: cache-modules
  #       uses: actions/cache@v1
  #       with:
  #         path: node_modules
  #         key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}

  #     - name: Install dependencies
  #       if: steps.cache-modules.outputs.cache-hit != 'true'
  #       run: yarn install --immutable

  #     - name: Symlink
  #       run: yarn scaffold

  #     - name: Build
  #       run: yarn build

  #     - name: Setup git
  #       run: |
  #         git config --local user.email "action@github.com"
  #         git config --local user.name "GitHub Action"

  #     - name: Version
  #       run: yarn lerna:prerelease

  #     - name: Publish
  #       run: yarn release
